# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - shell: cmd
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
        consumer_key: ${{ secrets.CONSUMER_KEY }}
        consumer_secret: ${{ secrets.CONSUMER_SECRET }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node server.js
